---
- hosts: webservers

  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    user_name: Ahmed Ali


  tasks:

  # Redhat && Amazon linux

    - name: Install nginx
      yum:
        name: nginx
        state: latest 
        update_cache: yes      
      when: ansible_facts["os_family"]=='RedHat'


    - name: Insert Index Page
      template:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      when: ansible_facts["os_family"]=='RedHat'


    - name: enable nginx
      service:
        name: nginx
        state: started
      when: ansible_facts["os_family"]=='RedHat'




  # Ubuntu
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_facts["os_family"]=='Debian'   
    
    - name: Copy website files to the server's document root
      template:
        src: index.html
        dest: /var/www/html 
      when: ansible_facts["os_family"]=='Debian'  

   


    - name: Apply Nginx template
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx  
      when: ansible_facts["os_family"]=='Debian'    
 


    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
      when: ansible_facts["os_family"]=='Debian'    


  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted